### ISSUE TITLE
Text and image selection missing 

### ISSUE THREAD

**Issue by K-plus69** [Kingsman44/Pixelify#167]
Hello!
Is it possible to add the text and image selection while the user is in the active apps menu? It's a pixel exclusive.

By the way... Why does the Google recorder crash after saying one word? I downloaded German. And where can I find the options for call screening?

Thanks for the nice module tho!

**Comment by Reiux** [comment]
> Is it possible to add the text and image selection while the user is in the active apps menu? It's a pixel exclusive.

Hello! You need to install pixel launcher in order to use text and image selection but it only works on stock android roms running android 9 and above.

>And where can I find the options for call screening?

You need to install Phone by Google on APKMirror not on play store it's because it Play store gives you the "downloadable" version of the app. Instead read the picture below.

![Screenshot_2023-01-31-13-04-18-26_a2f4758f9c0a9fa4d0ad0d47e2b8dd16.jpg](https://user-images.githubusercontent.com/90865965/215660321-8c402a88-69b4-4a5e-bc3e-69e958f2ba2d.jpg)

After installing the app make it as system app for call screening to work. Search "app systemizer v17.4.1" and install the module. then install termux after that.

After systemizing the app install the module again and you should see a option asking you if you want to install call screening.

If Phone by Google is already a system app in your phone, uninstall the latest updates of the app and install the one that you the downloaded on apkmirror.

The call screening settings are in the 3 dot menu on the top right side of your screen then settings.

Troubleshooting

-It says App not installed.

To fix this install the module and after that try installing the app again.

Hope this helps!
