### ISSUE TITLE
Module saying my phone doesn't have internet

### ISSUE THREAD

**Issue by fuadhdmini** [Kingsman44/Pixelify#7]
Thus it can't download Nga resources and the rest that requires download. But I believe since I am using Pixel 5, those files should be there, no?

Device: Pixel 5
Android version: 12 Beta 3.1

I tried this module since I want Call Screening features since I'm not within US nor Canada.

P/s: can you make the Google Photos backup to replicate the privilege for Pixel first generation instead of Pixel 5?

Evolution X ROM has built in Google Photos original unlimited backup but no call screen.

**Comment by Kingsman44** [comment]
Sorry about that, looks like curl problem there, I will fix it on next release. Photos Unlimited backup is working here with module. I will retake a look on it. For about call screening. I will work on any rom.

I have Redmi Note 4 with Lineage OS. It also works there. It only need Google Dialer app :-) rest leave on module.

**Comment by fuadhdmini** [comment]
Since you're updating the module, perhaps you can also enable call
recording also with Google dialer.

Since it's currently only supported for certain countries according to
Google support page.

Thanks.

**Comment by Kingsman44** [comment]
Pixelify module enables Call Recording on Countries supporting Call Recording on any device.

Since my country already listed in supported country, I Don't know about others whether they work or not. 

On next update I will try to add For all countries but can't promise about it. Cause it's already enabled on my country so it's difficult to test for me whether it's will be Enabled or not.

**Comment by fuadhdmini** [comment]
Ok, thanks.

**Comment by fuadhdmini** [comment]
Just flashed 1.5. i can see call recording option!

Thanks. Youre the best!
